# Generated by Django 4.1.5 on 2023-03-24 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeapp', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('firs_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('address', models.CharField(max_length=700, verbose_name='address')),
                ('zarinpal_authority', models.CharField(blank=True, max_length=255)),
                ('orders_notes', models.CharField(blank=True, max_length=700, verbose_name='Order Note')),
                ('datatime_create', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('datatime_modified', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='storeapp.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
