# Generated by Django 4.1.5 on 2023-03-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_myx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyX',
        ),
    ]
