# Generated by Django 4.1.5 on 2023-04-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
